### ISSUE TITLE
Dependency issue?

### ISSUE THREAD

**Issue by sndrs** [megawac/lodash-modularize#11]
Hi there,

I'm trying to work out exactly which lodash modules we're using on the guardian, but running `lodash-modularize ./**/*.js --list` i get the following error:

```
Unhandled rejection TypeError: Cannot read property 'charAt' of undefined
    at Object.posix.isAbsolute (path.js:479:14)
    at posix.normalize (path.js:461:26)
    at matchesPath (/usr/local/lib/node_modules/lodash-modularize/dist/parseForModules.js:46:99)
    at /usr/local/lib/node_modules/lodash-modularize/dist/parseForModules.js:112:12
    at arrayFilter (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:1384:13)
    at filter (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:6309:14)
    at interceptor (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:12240:43)
    at thru (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:5927:26)
    at baseWrapperValue (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:2768:30)
    at LazyWrapper.lazyValue [as value] (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:1077:16)
    at baseWrapperValue (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:2761:25)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:6124:14)
    at LazyWrapper.lazyValue [as value] (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:1061:36)
    at baseWrapperValue (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:2761:25)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/lodash-modularize/node_modules/lodash/index.js:6124:14)
    at exports.default (/usr/local/lib/node_modules/lodash-modularize/dist/parseForModules.js:133:6)
From previous event:
    at /usr/local/lib/node_modules/lodash-modularize/dist/lodash-modularize.js:41:48
From previous event:
    at resolve (/usr/local/lib/node_modules/lodash-modularize/dist/lodash-modularize.js:40:32)
    at /usr/local/lib/node_modules/lodash-modularize/dist/lodash-modularize.js:51:12
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at modularize (/usr/local/lib/node_modules/lodash-modularize/dist/lodash-modularize.js:50:107)
    at Object.<anonymous> (/usr/local/lib/node_modules/lodash-modularize/bin/lodash-modularize:131:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

does `lodash-modularize` support recursive searching?

thanks for making this - if this can work it will be a lifesaver :)

**Comment by megawac** [comment]
I think this happens if you use a variable instead of a string for a require

```
var some_module = 'x';
require(some_module)
```

**Comment by megawac** [comment]
@sndrs can you confirm this or are you running into this from a different situation?
